import type { ChunkRecord } from "./types";

const CHUNK_LABELS: Record<string, string> = {
  "exp-dug-overview": "Devs United Games",
  "exp-dug-partnerships": "DUG Partnerships",
  "exp-dug-revenue": "DUG Revenue",
  "exp-dug-apple-spatial": "Apple Spatial Computing",
  "exp-dug-ai-ops": "DUG AI Ops",
  "experience-devs-united-games-scaling": "DUG Scaling",
  "exp-flint-overview": "Flint Technologies",
  "exp-flint-product-gtm": "Flint Product & GTM",
  "exp-flint-fundraising": "Flint Fundraising",
  "experience-flint-technologies-zero-to-one": "Flint Zero-to-One",
  "exp-tmax-team-lead": "Tmax Team Lead",
  "exp-tmax-enterprise-clients": "Enterprise Clients",
  "exp-tmax-software-engineer": "Tmax Engineering",
  "exp-kit-research": "KIT Research",
  "edu-kaist-bachelors": "KAIST B.S.",
  "edu-kaist-masters": "KAIST M.S.",
  "edu-kit-dual-degree": "KIT Dual Degree",
  "story-meta-quest-plus-revenue": "Meta Quest+ Revenue",
  "story-apple-partnership-negotiation": "Apple Partnership",
  "story-meta-funding-negotiation": "Meta Negotiation",
  "story-meta-game-concepts": "Meta Game Concepts",
  "story-google-android-xr-partnership": "Google Android XR",
  "story-partnership-negotiation-philosophy": "Partnership Philosophy",
  "story-dug-cs-automation": "CS Automation",
  "story-flint-problem-statement": "Flint Problem",
  "story-flint-product-concept": "Flint Product",
  "story-flint-validation-traction": "Flint Traction",
  "story-flint-business-model-growth": "Flint Business Model",
  "story-flint-gnn-technical": "GNN Technical",
  "story-flint-founder-equity-split": "Founder Equity",
  "story-tmax-database-tuning": "Database Tuning",
  "story-tmax-samsung-dbms-monitoring": "Samsung DBMS",
  "project-whiskey-rag": "RAG Project",
  "story-whiskey-rag-personal": "RAG Personal Story",
  "flint-seed-round-details": "Seed Round",
  "flint-fundraising-challenges": "Fundraising Challenges",
  "narrative-partnership-expertise": "Partnership Expertise",
  "narrative-embracing-challenges-and-learning": "Challenges & Learning",
  "summary-bridging-tech-and-business": "Tech × Business",
  "skills-expertise": "Skills & Expertise",
  "languages-international": "Languages",
  "extracurricular-atrium": "Leadership",
  "honors-awards": "Awards",
  "contact-info": "Contact",
  "interview-q1.1-self-introduction": "Self-Introduction",
  "interview-q2.1-why-vc": "Why VC",
  "interview-q2.3-five-year-vision-altos": "5-Year Vision",
  "interview-q2.4-altos-receive": "What From Firm",
  "interview-q3.1-engineer-to-business": "Engineer → Business",
  "interview-q3.2-tmaxtibero-lessons": "Tmax Lessons",
  "interview-q3.3-flint-shutdown": "Flint Shutdown",
  "interview-q3.4-dug-departure": "Why Left DUG",
  "interview-q3.5-breadth-strength-weakness": "Breadth vs Depth",
  "interview-q4.1-founder-philosophy": "Founder Philosophy",
  "interview-q4.2-good-vs-bad-investor": "Good vs Bad Investor",
  "interview-q4.3-restart-flint": "Restart Flint",
  "interview-q4.4-fundraising-hardest-part": "Fundraising Challenge",
  "interview-q4.5-shutting-down-flint-emotions": "Shutdown Emotions",
  "interview-q4.6-founding-again": "Founding Again?",
  "interview-q4.7-confidence-after-failure": "Confidence & Failure",
  "interview-q5.1-ace-evidence": "Ace Evidence",
  "interview-q5.2-beyond-expectations-example": "Beyond Expectations",
  "interview-q5.3-colleague-evaluation": "Colleague Evaluation",
  "interview-q13.2-handling-disagreement": "Handling Disagreement",
  "final-q1-finding-founders-sourcing": "Deal Sourcing",
  "final-q6-stress-mental-resilience": "Stress & Resilience",
  "final-q11-self-initiated-knowledge-system": "Self-Initiated Projects",
  "final-q8-what-makes-you-different": "What Makes DJ Different",
  "final-q9-why-hire-over-vc-experience": "Why Hire DJ",
  "final-q19-team-over-self-altruism": "Team Over Self",
  "final-q13-explosive-growth-jcurve": "Growth Experience",
  "final-q33-ten-year-vision": "10-Year Vision",
  "changjo-2026-current-role": "Changjo Current Role",
  "dug-meta-quest-plus-deal": "Meta Quest+ Deal",
  "dug-google-android-xr-partnership": "Google Android XR",
  "dug-walking-away-meta-funding": "Meta Funding Walk-Away",
  "education-kaist-kit": "KAIST & KIT Education",
  "technical-skills-overview": "Technical Background",
  "changjo-smart-farm-initiative": "Smart Farm Initiative",
  "languages-international-experience": "Languages & International",
  "tmaxtibero-technical-work": "TmaxTibero Technical",
  "leadership-cross-functional-management": "Cross-Functional Leadership",
};

const ALWAYS_PINNED = new Set(["narrative-career-trajectory", "personal-summary", "contact-info"]);
const MAX_SOURCE_TAGS = 3;

export function getSourceTags(chunks: readonly ChunkRecord[]): string[] {
  return [...new Set(chunks.filter(chunk => !ALWAYS_PINNED.has(chunk.id))
    .map(chunk => CHUNK_LABELS[chunk.id]).filter((label): label is string => Boolean(label)))].slice(0, MAX_SOURCE_TAGS);
}
