-- Fresh installation only. See README.md before adopting an existing database.
begin;

create table public.app_settings (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

create table public.analytics_events (
  id integer generated by default as identity primary key,
  created_at timestamptz not null default now(),
  type text not null,
  session_id text,
  persona text,
  focus text,
  lang text,
  query text,
  chunks_retrieved integer,
  chunks_after_rerank integer,
  message_id text,
  feedback_value text,
  visitor_email text
);

create table public.chat_exchanges (
  id integer generated by default as identity primary key,
  created_at timestamptz not null default now(),
  session_id text not null,
  persona text not null,
  focus text not null,
  lang text not null,
  query text not null,
  response text not null,
  chunks_used text[] default '{}',
  visitor_email text,
  source text,
  dj_rating text check (dj_rating in ('good', 'needs_improvement')),
  dj_comment text,
  improvement_text text,
  pinecone_chunk_id text,
  reviewed_at timestamptz
);

create index chat_exchanges_created_id_idx on public.chat_exchanges (created_at, id);
create index chat_exchanges_session_created_id_idx on public.chat_exchanges (session_id, created_at, id);
create index chat_exchanges_review_idx on public.chat_exchanges (reviewed_at, dj_rating, created_at, id);
create index analytics_events_session_created_idx on public.analytics_events (session_id, created_at);

alter table public.app_settings enable row level security;
alter table public.analytics_events enable row level security;
alter table public.chat_exchanges enable row level security;

revoke all on public.app_settings, public.analytics_events, public.chat_exchanges from anon, authenticated;
revoke all on sequence public.analytics_events_id_seq, public.chat_exchanges_id_seq from anon, authenticated;
grant all on public.app_settings, public.analytics_events, public.chat_exchanges to service_role;
grant usage, select on sequence public.analytics_events_id_seq, public.chat_exchanges_id_seq to service_role;
-- No public RLS policies. Only server-side service-role credentials access these tables.

commit;
